volumes:
  unluckiest_database:

services:

  database:
    image: mariadb:latest
    container_name: database
    environment:
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - unluckiest_database:/var/lib/mysql
    networks:
      -  unluckiest_network
    ports:
      - "9000:3306"

  api:
    container_name: api
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_URL: mysql://mariadb_test:3306/unluckiest_database
      DB_USER: user
      DB_PASSWORD: _unlckst_prod!
    networks:
      - storage_network
    depends_on:
      - database

networks:
  unluckiest_network: